projects can modify NAME and default squishy in Makefile.config, so that way luce_embedded can be cloned and updated without conflicts with projects customisations

diff --git a/get_lua_deps b/get_lua_deps
--- a/get_lua_deps
+++ b/get_lua_deps
@@ -1,4 +1,8 @@
 #!/usr/bin/env bash
 
-modules=$(cat squishy |grep -E '(^Main|^Module)'|awk '{print $NF}'|xargs)
+! [[ -f "$1" ]] && echo "ERROR: Missing squishy" && exit 1
+
+squishy="$1"
+
+modules=$(cat "$squishy" |grep -E '(^Main|^Module)'|awk '{print $NF}'|xargs)
 echo "$modules"
